spring.application.name=sed
server.port=16000

spring.datasource.url=jdbc:postgresql://localhost:5432/sed_db
spring.datasource.username=postgres
spring.datasource.password=Sebitas123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
